# Setup
title:            Medical Markdown
tagline:          > # this means to ignore newlines until "baseurl:"
  Specification for the Medical Markdown system of generating structured clinical data along AoMRC headings from plain text using text tags.
baseurl:          "/docs"
paginate:         1
twitter_username: marcus_baw
github_username:  pacharanero

# About/contact
author:
  name:           Marcus Baw
  url:            http://pacharanero.github.io/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown